class MasterMind

	require_relative 'init'
	require_relative 'input'
	require_relative 'feedback'
	require_relative 'victory'
	require_relative 'cpu_ai'

	def initialize(cpu)
		@cpu_player = cpu
		puts @cpu_player
		setup_game
		new_turn
	end

	private

	def new_turn
		guess = @cpu_player ? cpu_guess : get_valid_code
		p guess
		if victory?(guess)
			game_over
		else
			@turns.increment
			feedback_msgs(guess)
			interpret_feedback(guess) if @cpu_player
			@turns.count < @max_turns ? new_turn : game_over(false)
		end
	end

end

def cpu_player?
	type = gets.chomp.downcase
	if type == "make"
		game = MasterMind.new(true)
	elsif type == "crack"
		game = MasterMind.new(false)
	else
		puts "I didn't get that. Type 'make' or 'crack'."
		cpu_player?
	end
end


puts "Do you want to make a code or crack a code generated by the computer?"
cpu_player?
